theme_index:
    path:     /
    defaults: { _controller: "ProjetBundle:Theme:index" }
    methods:  GET

theme_show:
    path:     /{idTheme}/show
    defaults: { _controller: "ProjetBundle:Theme:show" }
    methods:  GET

theme_new:
    path:     /new
    defaults: { _controller: "ProjetBundle:Theme:new" }
    methods:  [GET, POST]

theme_edit:
    path:     /{idTheme}/edit
    defaults: { _controller: "ProjetBundle:Theme:edit" }
    methods:  [GET, POST]

theme_delete:
    path:     /{idTheme}/delete
    defaults: { _controller: "ProjetBundle:Theme:delete" }
    methods:  DELETE
